# LibraryBuild.yml
# Github workflow script to test compile all examples of an Arduino library repository.
#
# Copyright (C) 2020  Armin Joachimsmeyer
# https://github.com/ArminJo/Github-Actions
#

# This is the name of the workflow, visible on GitHub UI.
name: LibraryBuild
on:
  push: # see: https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
    paths:
    - '**.ino'
    - '**.cpp'
    - '**.h'
    - '**LibraryBuild.yml'
  pull_request:

jobs:
  build:
    name: ${{ matrix.arduino-boards-fqbn }} - test compiling examples

    runs-on: ubuntu-18.04 # I picked Ubuntu to use shell scripts.

    strategy:
      matrix:
        # The matrix will produce one job for each configuration parameter of type `arduino-boards-fqbn`
        # In the Arduino IDE, the fqbn is printed in the first line of the verbose output for compilation as parameter -fqbn=... for the "arduino-builder -dump-prefs" command
        #
        # Examples: arduino:avr:uno, arduino:avr:leonardo, arduino:avr:nano, arduino:avr:mega
        # arduino:sam:arduino_due_x, arduino:samd:arduino_zero_native"
        # ATTinyCore:avr:attinyx5:chip=85,clock=1internal, digistump:avr:digispark-tiny, digistump:avr:digispark-pro
        # STM32:stm32:GenF1:pnum=BLUEPILL_F103C8
        # esp8266:esp8266:huzzah:eesz=4M3M,xtal=80, esp32:esp32:featheresp32:FlashFreq=80
        # You may add a suffix behind the fqbn with "|" to specify one board for e.g. different compile options like arduino:avr:uno|trace
        #############################################################################################################
        arduino-boards-fqbn:
          - arduino:avr:uno
          - arduino:avr:mega
          - arduino:megaavr:nona4809:mode=off
          - arduino:samd:arduino_zero_native
          - digistump:avr:digispark-tiny16
          - digistump:avr:digispark-pro
          - ATTinyCore:avr:attinyx5:chip=85,clock=8internal
          - esp8266:esp8266:d1_mini:eesz=4M3M,xtal=80
          - esp32:esp32:featheresp32:FlashFreq=80
          - STM32:stm32:GenF1:pnum=BLUEPILL_F103C8
          - stm32duino:STM32F1:genericSTM32F103C
          #- SparkFun:apollo3:amap3nano # All examples give strange BFD assertions

        # Specify parameters for each board.
        # With examples-exclude you may exclude specific examples for a board. Use a comma separated list.
        #############################################################################################################
        include:
          - arduino-boards-fqbn: digistump:avr:digispark-tiny16
            platform-url: https://raw.githubusercontent.com/ArminJo/DigistumpArduino/master/package_digistump_index.json
            examples-exclude: AllProtocols,ReceiveAndSendDynamicPins # Does not fit in FLASH # Comma separated list of (unique substrings of) example names to exclude in build

          - arduino-boards-fqbn: digistump:avr:digispark-pro
            platform-url: https://raw.githubusercontent.com/ArminJo/DigistumpArduino/master/package_digistump_index.json
            examples-exclude: ReceiveAndSendDynamicPins # No Serial.available

          - arduino-boards-fqbn: ATTinyCore:avr:attinyx5:chip=85,clock=8internal
            platform-url: http://drazzy.com/package_drazzy.com_index.json
            examples-exclude: AllProtocols,ReceiveAndSendDynamicPins # Does not fit in FLASH, No Serial.available

          - arduino-boards-fqbn: esp8266:esp8266:d1_mini:eesz=4M3M,xtal=80
            platform-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
            examples-exclude: AllProtocols # error ".text1' will not fit in region `iram1_0_seg'"

          - arduino-boards-fqbn: esp32:esp32:featheresp32:FlashFreq=80
            platform-url: https://dl.espressif.com/dl/package_esp32_index.json

          - arduino-boards-fqbn: STM32:stm32:GenF1:pnum=BLUEPILL_F103C8
            platform-url: https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json

          - arduino-boards-fqbn: stm32duino:STM32F1:genericSTM32F103C # Roger Clark version
            platform-url: http://dan.drown.org/stm32duino/package_STM32duino_index.json

          # ALL examples give strange BFD assertions
          #- arduino-boards-fqbn: SparkFun:apollo3:amap3nano
          #  platform-url: https://raw.githubusercontent.com/sparkfun/Arduino_Boards/master/IDE_Board_Manager/package_sparkfun_index.json

      # Do not cancel all jobs / architectures if one job fails
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Compile all examples
        uses: ArminJo/arduino-test-compile@master
        with:
          arduino-board-fqbn: ${{ matrix.arduino-boards-fqbn }}
          platform-url: ${{ matrix.platform-url }}
          examples-exclude: ${{ matrix.examples-exclude }}
